✨ Implement Interactive UI
purduesigbots/pros-atom3 pull request #32
Opened 2019-01-12 18:45 UTC by edjubuh

### Summary

- Implement interactive UI. Interactive UI is a way for the CLI to present the UI to the users and have a (possibly) external presenter worry only about presentation of the CLI's requested elements and alerting the CLI to changes to those elements. The CLI then is responsible for deciding what UI elements are needed and the relevant business logic

### Test Plan

WIP

#### References

WIP

2019-01-12 22:28 UTC, HotelCalifornia reviewed
Just a couple of code style things.

- Double check that etch allows the use of `class` in jsx nodes (I know react doesn't).
- make sure that all strings are single-quoted (except when used as jsx attributes)

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/applications/modal.js
> +      console.log('Attempting to show a destroyed panel')
Maybe a `console.warn` here

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/applications/modal.js
> +      console.log('Attempting to show a destroyed panel')
If it's even necessary, that is. Why not just recreate the panel in this case and then show it?

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/components/BasicParameterizedComponent.js
> +    if (!!this.text) {
The `if` statement ready coerces arguments to `bool` values, so the `!!` should be unnecessary

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/components/BasicParameterizedComponent.js
> +      <div class="pros-basic-parameter">
I don't remember whether etch does this differently, but I think this should be `className` instead (as `class` is a reserved word)

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/components/Button.js
> +      <button class={"btn"}
rm unnecessary `{}`

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/components/ButtonGroup.js
> +          <button class={"btn" + (item === this.value ? " selected" : "")}
Prefer declaring this a `const`. Also use a template literal over string concatenation with `+`:

```js
const cls = `btn${item === this.value ? ' selected' : ''}`
```

2019-01-12 22:28 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/components/ParameterizedComponent.js
> +      valid_reason = <div class={this.valid === false ? 'text-error' : 'text-warning'}>{this.valid_reason}</div>
Same nit as above wrt class values

2019-01-12 22:54 UTC, edjubuh commented on lib/middleware-linkage/input/interactive/applications/modal.js
> +      console.log('Attempting to show a destroyed panel')
> If it's even necessary, that is. Why not just recreate the panel in this case and then show it?

I'd rather leave it the way it is since this case shouldn't happen. I'd rather it not just silently work.

2019-01-12 22:59 UTC, HotelCalifornia commented on lib/middleware-linkage/input/interactive/applications/modal.js
> +      console.log('Attempting to show a destroyed panel')
Okay, then change it to a `warn`

2019-01-13 06:02 UTC, HotelCalifornia reviewed
make sure that JSX string attributes are double-quoted:

```jsx
<div className="cls">
```
**NOT**
```jsx
<div className='cls'>
```

One day I'll get a formatter running here, which will take care of all this for us...

2019-01-22 15:18 UTC, HotelCalifornia approved these changes
Looks like we've been consistently using single quotes for JSX attributes, so my previous comment can be ignored.

2019-01-22 15:20 UTC, HotelCalifornia commented
we'll have to remember to bump the version of the middleware once purduesigbots/pros-cli-middleware#4 gets merged and we're ready to release a new version of this package

2019-02-12 01:23 UTC, HotelCalifornia requested changes
revising my previous review. there's a couple of polish things I'd like to take care of before we merge this

2019-02-12 01:29 UTC, HotelCalifornia commented
- cancelling the upload project modal (possibly also others) results in an error notification that just shows the content `1`:
![](https://puu.sh/CKQW9/9d172a1572.png)
- in the upload project modal, project detection doesn't seem to work (though this may be more on the CLI side):
![](https://puu.sh/CKQZu/4b74b9ccb1.png)
- need to discuss how we want users to access the upload prompts. should the buttons on the toolbar open them by default? I don't think they should remain hidden in the command palette

2019-02-12 01:35 UTC, HotelCalifornia commented
one other note: when manually typing in a path, unless you type really quickly or fairly slowly, some input erasure can occur. there seems to be sort of a middle grey area where this happens

2019-02-12 02:04 UTC, HotelCalifornia commented on menus/pros-atom3.json
> +        },
hm. not sure how I feel about this. maybe better to have it always show the prompt from the menu? and add a setting that will control whether the button on the toolbar shows it or not?

2019-02-12 02:41 UTC, HotelCalifornia commented on menus/pros-atom3.json
> +        },
user feedback has led me to the conclusion that we should leave the toolbar button as-is, and replace the menu option with the `upload-prompt` command

2019-02-12 02:56 UTC, Razat101 commented
- Adding template: So I would have no idea what to type into that text box and I don't know if anyone starting will know what to do with that. I don't know how it works but I think a drop-down list would be more user-friendly for new users. 
- Project rollback: I don't understand how this works but I think that it is saving your project from going completely bad or stopping the user from getting rid of things they need so that's very good.
- Creating a new V5/Cortex Project: I do not think the things hidden under advanced need to be hidden. I think they should always be showing.
- Upgrading: Yes. I love it. It's simple and needs little to no explaination to use. 
- Adding okapi: Same thing about adding a template. Can it just be a drop-down list of what you can add and it adds it.
- Downgrading and Removing: I like it. Simple and needs no explanation.
- Sentry prompt in interactive UI: If this is talking about sending a bug report, I'm concerned if this happens every time when I upload a project. I get that in the terminals a few times when I upload. Because sometimes I get 3 in a row. Is it possible that you can have a button to send all so if I do get multiple I do not have to individually click yes to all of them? If there is no possibility that you get more than one or it already sends them all then just disregard this.
- Uploading a V5 Project with port detection: I would love this so much. But again, I don't think it should the hide advanced option should be added, it should all be displayed. I believe this should pop up every time by default. But, is there a way to add a layout save. Like if you wanna keep on downloading to the 2nd port and not change your code in the 1st port it saves that information so that you keep on downloading to the port you last downloaded to. Reason being is one of my sister team has a coder that does skills and a coder that does driver control and auton and when the person who did skills accidentally overwrote the driver control program because they forgot to change the port, they couldn't practice for the rest of the day.

2019-02-12 03:04 UTC, edjubuh commented
Thanks for the feedback!
> * Adding template: So I would have no idea what to type into that text box and I don't know if anyone starting will know what to do with that. I don't know how it works but I think a drop-down list would be more user-friendly for new users.

I agree. Down the road (especially once we get more folks using templates 😄), I wanted to figure out how to get some sort of autocompletion working, rather than a dropdown. For now, I didn't want to worry about getting all that working since we really only distribute one template other than okapilib and if anyone messes with templates, it's gonna be just one or two that they already know the name for.
 
> * Creating a new V5/Cortex Project: I do not think the things hidden under advanced need to be hidden. I think they should always be showing.

I can do that on the CLI side. Do you mind opening an issue on purduesigbots/pros-cli? Or if you wanna make a PR directly - [this is your line](url).

> * Upgrading: Yes. I love it. It's simple and needs little to no explaination to use.
> * Downgrading and Removing: I like it. Simple and needs no explanation.

Glad it's easier to use.

> * Sentry prompt in interactive UI: If this is talking about sending a bug report, I'm concerned if this happens every time when I upload a project. I get that in the terminals a few times when I upload. Because sometimes I get 3 in a row. Is it possible that you can have a button to send all so if I do get multiple I do not have to individually click yes to all of them? If there is no possibility that you get more than one or it already sends them all then just disregard this.

Hmm... well you shouldn't be getting that many error messages. Perhaps it's related to purduesigbots/pros-cli#36

> * Uploading a V5 Project with port detection: I would love this so much. But again, I don't think it should the hide advanced option should be added, it should all be displayed.

Ditto from above - [here's the line](https://github.com/purduesigbots/pros-cli/blob/fcd08bc516c10e9b9785b707c056f36e752ee0b3/pros/serial/interactive/UploadProjectModal.py#L27).

2019-02-12 03:09 UTC, Jerrylum commented
As I said, add a slot review feature on the upload prompt.
Every time I upload and select a slot, I can see which slot has been used or empty. It is very good if it also displays the program name on that slot. So all user will not select the wrong slot accidentally and cover the other programs.

![image](https://user-images.githubusercontent.com/12783829/52608795-ece68780-2eb5-11e9-939d-bfca25a1905d.png)
Plan A:
When your mouse hold over the slot input column, a `Floating Description` shown
Plan B:
When your click the slot input column, a text shown below the input column

2019-02-12 03:14 UTC, HotelCalifornia commented
> As I said, add a slot review feature on the upload prompt.

This could be doable (not sure if we have tooltips implemented in the current version of interactive UI), but I feel like a somewhat more useful feature would be some sort of "file browser" tab. That would be out of scope of this PR though.

2019-02-12 13:48 UTC, edjubuh commented
> As I said, add a slot review feature on the upload prompt.
> Every time I upload and select a slot, I can see which slot has been used or empty. It is very good if it also displays the program name on that slot. So all user will not select the wrong slot accidentally and cover the other programs.

That shouldn't be too hard to implement. I'm thinking instead of a textbox, a dropdown with all the slots. If there's a program loaded in that slot, then it would say something like
- 1 (okapi_clawbot)
- 2
- 3 (kernel)
- 4
- 5
- 6
- 7
- 8

To do this would require changes only on the CLI. Do you mind opening an issue on purduesigbots/pros-cli?

2019-02-18 03:13 UTC, HotelCalifornia approved these changes

2019-02-18 03:47 UTC, merged